city: "hamburg"
country: "Germany"
radius: 25
immoType: "wohnungen"
intend: "mieten"
bjmi: "" #Bauhjahr ab
bjma: "" #Bauhjahr bis
roomi: "" #Zimmer ab
rooma: "" #Zimmer bis
wflmi: "" #Wohnfläche ab
wflma: "" #Wohnfläche bis
primi: "" #Preis ab
prima: "" #Preis bis
